# Setup
title:        scramble-text-js
tagline:      A library that scrambles a text and over some time gradually unscrambles it.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       "@javorszky"
  url:        https://twitter.com/javorszky 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown